### ISSUE TITLE
Error: error:1E08010C:DECODER routines::unsupported when calling the api

### ISSUE THREAD

**Issue by Chocrates** [octokit/auth-app.js#332] opened 2021-12-10 21:27 UTC
I received the following error:

```
node:internal/crypto/sig:131
  const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
                            ^

Error: error:1E08010C:DECODER routines::unsupported
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/home/ubuntu/okta-webhooks/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/home/ubuntu/okta-webhooks/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/home/ubuntu/okta-webhooks/node_modules/jsonwebtoken/sign.js:204:16)
    at getToken (/home/ubuntu/okta-webhooks/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)
    at Object.githubAppJwt (/home/ubuntu/okta-webhooks/node_modules/universal-github-app-jwt/dist-node/index.js:35:23)
    at getAppAuthentication (/home/ubuntu/okta-webhooks/node_modules/@octokit/auth-app/dist-node/index.js:110:59)
    at getInstallationAuthentication (/home/ubuntu/okta-webhooks/node_modules/@octokit/auth-app/dist-node/index.js:269:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async hook (/home/ubuntu/okta-webhooks/node_modules/@octokit/auth-app/dist-node/index.js:449:7) {
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}

Node.js v17.2.0
```

```js
const { createAppAuth } = require("@octokit/auth-app");
const { Octokit } = require("@octokit/rest");

const installationOctokit = new Octokit({
  authStrategy: createAppAuth,
  auth: {
    appId: process.env.APP_ID,
    privateKey: process.env.APP_PRIVATE_KEY,
    installationId: process.env.INSTALLATION_ID,
  },
});
let out = await installationOctokit.repos.listForOrg({
  org: "chocrates-test-org",
});
console.log(out);
```

Using node17.

I downgraded to node16 and moved the Pkey to a file and it started working.

**Comment by Kaktus259** [comment] 2022-02-02 01:21
> I received the following error:
> 
> ```
> node:internal/crypto/sig:131
>   const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
>                             ^
> 
> Error: error:1E08010C:DECODER routines::unsupported
>     at Sign.sign (node:internal/crypto/sig:131:29)
>     at Object.sign (/home/ubuntu/okta-webhooks/node_modules/jwa/index.js:152:45)
>     at Object.jwsSign [as sign] (/home/ubuntu/okta-webhooks/node_modules/jws/lib/sign-stream.js:32:24)
>     at Object.module.exports [as sign] (/home/ubuntu/okta-webhooks/node_modules/jsonwebtoken/sign.js:204:16)
>     at getToken (/home/ubuntu/okta-webhooks/node_modules/universal-github-app-jwt/dist-node/index.js:13:23)
>     at Object.githubAppJwt (/home/ubuntu/okta-webhooks/node_modules/universal-github-app-jwt/dist-node/index.js:35:23)
>     at getAppAuthentication (/home/ubuntu/okta-webhooks/node_modules/@octokit/auth-app/dist-node/index.js:110:59)
>     at getInstallationAuthentication (/home/ubuntu/okta-webhooks/node_modules/@octokit/auth-app/dist-node/index.js:269:35)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async hook (/home/ubuntu/okta-webhooks/node_modules/@octokit/auth-app/dist-node/index.js:449:7) {
>   library: 'DECODER routines',
>   reason: 'unsupported',
>   code: 'ERR_OSSL_UNSUPPORTED'
> }
> 
> Node.js v17.2.0
> ```
> 
> ```
> const { createAppAuth } = require("@octokit/auth-app");
>   const { Octokit } = require("@octokit/rest");
> 
>       const installationOctokit = new Octokit({
>           authStrategy: createAppAuth,
>           auth: {
>             appId: process.env.APP_ID,
>             privateKey: process.env.APP_PRIVATE_KEY,
>             installationId: process.env.INSTALLATION_ID,
>           },
>       });
> let out = await installationOctokit.repos.listForOrg({
>               org: "chocrates-test-org",
>           });
>           console.log(out);
> ```
> 
> Using node17.
> 
> I downgraded to node16 and moved the Pkey to a file and it started working.

**Comment by mi-hol** [comment] 2022-07-12 08:41
Hit the same error in a next.js demo app too.

I tried to follow the demo README but for any NOOB certain steps require knowledge to be done correctly that a NOOB simply wont have.
Therefore errors are to be expected and **only meaningful error messages help to get over these hurdles.**
This fact applies to later application support too!

Please see https://github.com/vercel/next.js/discussions/38385#discussioncomment-3120467 for details

**Comment by timrogers** [comment] 2022-07-12 17:13
@mi-hol I did some googling of their error message, and it seems like a common cause of the error is having an incorrectly formatted private key (e.g. [this StackOverflow answer](https://salesforce.stackexchange.com/a/365817). 

Can you double check that the `privateKey` you are supplying is correctly formatted?

**Comment by mi-hol** [comment] 2022-07-17 18:23
> This isn't an error message that we throw, it is from NodeJS. There isn't anything we can do for that. We always try to have meaningful error messages throughout the Octokit modules.

Thanks for pointing to NodeJS as the proper place to report this issue to

> I really dislike the attitude you are portraying in your comment. There is no need to have a bad attitude when reporting an issue here.

Apologize, I tried to be respectful but had searched for the root cause and a fix already for more than a day unsuccessfully. As unspecific error message have been a repeated/permanent issue in my career as application supporter I mentioned it without an intent of blaming anybody

**Comment by mi-hol** [comment] 2022-07-17 18:45
> it seems like a common cause of the error is having an incorrectly formatted private key

@timrogers thanks for the hint that lead to the resolution.
A "common cause"  would from my view have many more than 2 hits I got using [search string +js +"ERR_OSSL_UNSUPPORTED"](https://duckduckgo.com/?q=%2Bjs+%2B%22ERR_OSSL_UNSUPPORTED%22&t=vivaldi&ia=web).
May I kindly ask for the search string you used to find the?

**Comment by timrogers** [comment] 2022-07-18 12:07
No problem! I searched the same thing as you pretty much - I just saw the result and figured it would be the answer 😊 I'm going to close this issue - do feel free to reopen or create a new one if you run into other problems!

**Closed by timrogers** 2022-07-18 12:07 UTC
Labels: support
