### ISSUE TITLE
[BUG]: unable to use this package with `@actions/github-script`

### ISSUE THREAD

**Issue by shaneholder** [octokit/auth-app.js#499] opened 2023-06-19 21:29 UTC
### What happened?

It looks like between 5.0.4 and 5.0.5 dependencies were updated.  I suspect that the upgrade from @octokit/request 6.0.0 to 7.0.0 may have caused this issue.

The following code throws an error in 5.0.5 when run under actions/github-script@v6

```
const { createAppAuth } = require("@octokit/auth-app");
const key = `${{ secrets.PrivKey }}`

var auth = createAppAuth({appId: "${{vars.APPID}}", privateKey: key });            
var authentication = await auth({type: "installation", installationId: "${{vars.INSTALLID}}" })

return authentication.token  
```

Error:
```
Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.
    at fetchWrapper (/home/runner/work/tf-project/tf-project/node_modules/@octokit/request/dist-node/index.js:56:11)
    at newApi (/home/runner/work/tf-project/tf-project/node_modules/@octokit/request/dist-node/index.js:176:14)
    at getInstallationAuthentication (/home/runner/work/tf-project/tf-project/node_modules/@octokit/auth-app/dist-node/index.js:238:13)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:34:[22](https://github.com/sah-test/tf-project/actions/runs/5316189964/jobs/9625440887#step:4:23))
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15[23](https://github.com/sah-test/tf-project/actions/runs/5316189964/jobs/9625440887#step:4:24)6:20)
Error: Unhandled error: Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.
```

Makes me also wonder if the semver should be bumped by a major version if dependencies are bumped by a major version..

Thanks,
Shane

### Versions

@octokit/auth-app@5.0.5 actions/github-script@v6

### Relevant log output

```shell
Run actions/github-script@v6
  with:
    script: const { createAppAuth } = require("@octokit/auth-app");
  const key = `***
  `
  
  var auth = createAppAuth({appId: "***", privateKey: key });            
  var authentication = await auth({type: "installation", installationId: "***" })
  
  return authentication.token  
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,422
  env:
    WORKING_DIR: .
    ENVIRONMENT: development
Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.
    at fetchWrapper (/home/runner/work/tf-project/tf-project/node_modules/@octokit/request/dist-node/index.js:56:11)
    at newApi (/home/runner/work/tf-project/tf-project/node_modules/@octokit/request/dist-node/index.js:176:14)
    at getInstallationAuthentication (/home/runner/work/tf-project/tf-project/node_modules/@octokit/auth-app/dist-node/index.js:238:13)
    at async eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:34:22)
    at async main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:20)
Error: Unhandled error: Error: Global "fetch" not found. Please provide `options.request.fetch` to octokit or upgrade to node@18 or newer.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment] 2023-06-19 21:37
What version of Node JS is it running under? We dropped support for anything lower than Node v18, and we also stopped using `node-fetch` to instead use the Fetch API.

**Comment by JMoserCricut** [comment] 2023-06-20 16:27
yes this is still an issue with node 18:
![image](https://github.com/octokit/auth-app.js/assets/59970772/b19e1e45-7960-4ced-a590-0739af24b55e)

**Comment by wolfy1339** [comment] 2023-06-20 16:34
That's odd. You need to pass a fetch API polyfill, like `node-fetch` because it seems that the fetch API is disabled on the version of node you use

**Comment by JMoserCricut** [comment] 2023-06-20 16:54
@wolfy1339 As @shaneholder pointed out the update to the request.js (which includes [breaking changes](https://github.com/octokit/request.js/releases/tag/v7.0.0)) should've marked this v5.0.5 release as a breaking change rather than a patch change. I suggest that the v5.0.5 be reverted and re-released as a major change release since it includes breaking changes

**Comment by wolfy1339** [comment] 2023-06-20 17:48
It could be disabled in the builds they use, as it's still marked as experimental

https://nodejs.org/en/blog/announcements/v18-release-announce

**Comment by wolfy1339** [comment] 2023-06-20 17:54
That shouldn't be the case, as we use GitHub actions with `setup-node` and it works just fine

**Comment by JMoserCricut** [comment] 2023-06-20 19:50
I think it may be that both @shaneholder and I are using the octokit/auth-app wrapped within the [actions/github-script](https://github.com/actions/github-script) which provides it's own reference to fetch and only supports up to node 16 [it seems](https://github.com/actions/github-script/issues/310)

**Comment by shaneholder** [comment] 2023-06-21 13:53
Can confirm, I am also using github-script.

**Comment by myml** [comment] 2023-07-12 08:09
fetch not in global object, add `global["fetch"] = fetch` to the first line of script can fix it.

**Comment by UTsweetyfish** [comment] 2023-07-12 09:29
Should it be caused by [`@octokit/request`](https://togithub.com/octokit/request.js)?

https://github.com/octokit/request.js/commit/517ebabc60af2b44c0aa83600e8ca73aa5caa7d8#diff-e25dfcb05e38ef790c0894be934f090e2f095a8bf496aae32e908d7356b10c8cL29-R37

**Comment by wolfy1339** [comment] 2023-07-12 10:08
> fetch not in global object, add `global["fetch"] = fetch` to the first line of script can fix it.

That is not a sensible solution.

Simply pass a fetch polyfill in `options.request.fetch`

**Comment by wolfy1339** [comment] 2023-07-12 10:12
The newer versions of this package are incompatible with `@actions/github-script` since it does not have Node 18.

There is nothing for us to do here

**Closed** 2023-07-12 10:12 UTC
Labels: Type: Support

**Comment by chandrakanthbala** [comment] 2023-07-12 19:31
I'm facing the same issue. Can someone please let me know what is the resolution for this with below configuration?

Runner: `ubuntu-latest`
Node Version On Runner: 18.16.1
Using: actions/github-script@v6.4.1

**Comment by chandrakanthbala** [comment] 2023-07-12 19:39
@wolfy1339 How to pass a fetch polyfill in options.request.fetch?

**Comment by KevinMSampson** [comment] 2023-07-12 19:49
> yes this is still an issue with node 18: ![image](https://user-images.githubusercontent.com/59970772/247184886-b19e1e45-7960-4ced-a590-0739af24b55e.png)
> 
> pinning to v5.0.4 resolves the issue for us, even using node 16... ![image](https://user-images.githubusercontent.com/59970772/247185936-c03bcc58-5cc0-47f3-9434-e356cabf859a.png)

@chandrakanthbala 
This reply has a good example

```yaml
     - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      # NOTE: Temporary fix - https://github.com/octokit/auth-app.js/issues/499#issuecomment-1599121855
      - name: npm install @octokit/rest@v19.0.13 @octokit/auth-app@v5.0.4
        run: |
          npm install @octokit/rest@v19.0.13 @octokit/auth-app@v5.0.4
...
```

I noticed that since I follow the [octokit document](https://octokit.github.io/rest.js/v19#authentication) example using `@octokit/rest` too, I made sure to pin to an older version of that too. Pinning `@octokit/auth-app@v5.0.4` wasn't enough.

**Comment by chandrakanthbala** [comment] 2023-07-12 20:35
@KevinMSampson Thanks Kevin :smiley:

I misread that and didn't pin the Node version to 16. This solved the issue.

> > yes this is still an issue with node 18: ![image](https://user-images.githubusercontent.com/59970772/247184886-b19e1e45-7960-4ced-a590-0739af24b55e.png)
> > pinning to v5.0.4 resolves the issue for us, even using node 16... ![image](https://user-images.githubusercontent.com/59970772/247185936-c03bcc58-5cc0-47f3-9434-e356cabf859a.png)
> 
> @chandrakanthbala This reply has a good example
> 
> ```yaml
>      - uses: actions/setup-node@v3
>         with:
>           node-version: 16
>       
>       # NOTE: Temporary fix - https://github.com/octokit/auth-app.js/issues/499#issuecomment-1599121855
>       - name: npm install @octokit/rest@v19.0.13 @octokit/auth-app@v5.0.4
>         run: |
>           npm install @octokit/rest@v19.0.13 @octokit/auth-app@v5.0.4
> ...
> ```
> 
> I noticed that since I follow the [octokit document](https://octokit.github.io/rest.js/v19#authentication) example using `@octokit/rest` too, I made sure to pin to an older version of that too. Pinning `@octokit/auth-app@v5.0.4` wasn't enough.

@KevinMSampson Thanks Kevin :smiley:

I misread that and didn't pin the Node version to 16. This solved the issue.
